# Generated by Django 2.2.3 on 2019-09-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190924_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='hotel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chambre', to='main.Hotel'),
        ),
    ]
