# Generated by Django 2.2.3 on 2019-09-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190924_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
