# Generated by Django 2.2.3 on 2019-09-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_chambre_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='prix',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='etoile',
            field=models.IntegerField(default=3),
        ),
    ]
